<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Product;
use AppBundle\Entity\Category;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCategoriesWithProducts(){
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT a,c FROM AppBundle:Category a
                              LEFT JOIN a.products c
                              WHERE a.parent IS NULL');
        return $query->getResult();
    }


    public function findProductsByCategory(int $limit = 0, int $offset = 0,
                                                        int $categoryId = -1)
    {
        $categoryFilter = '';

        $em = $this->getEntityManager();
        if ($categoryId > -1) {
            $categoryFilter = " AND c.id = $categoryId" ;
        }
        $query = $em->createQuery("SELECT a,c FROM AppBundle:Product a
                                       JOIN a.category c
                                       WHERE a.isActive = '1' " . $categoryFilter
            .                         'ORDER BY a.price ASC');

        $query->setFirstResult($offset);
        $query->setMaxResults($limit);
        return $query->getResult();
    }


    public function getSubCategories(int $id){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT c FROM AppBundle:Category c
                                        WHERE c.parent = $id");
        return $query->getResult();
    }
}
