<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Promotion;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManager $em)
    {
        parent::__construct($em, new Mapping\ClassMetadata(Promotion::class));
    }

    public function findProductTypePromotions(){
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT p FROM AppBundle:Promotion p 
                                        WHERE p.type = 1');
        return $query->getResult();
    }

    public function findUserTypePromotions(){
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT p FROM AppBundle:Promotion p 
                                        WHERE p.type = 2');
        return $query->getResult();
    }
}
