<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Shipper;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping;

/**
 * ShipperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipperRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManager $em)
    {
        parent::__construct($em, new Mapping\ClassMetadata(Shipper::class));
    }
}
