<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCash(){
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT u FROM AppBundle:User u 
                                       WHERE u.cash > 1500');
        return $query->getResult();
    }
}
