<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManager $em)
    {
        parent::__construct($em, new Mapping\ClassMetadata(User::class));
    }

    public function findRichUsers(){
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT u FROM AppBundle:User u 
                                       WHERE u.cash > 1500');
        return $query->getResult();
    }
}
